In [1]:
import torch
import numpy as np

In [2]:
data = np.load('2d_data.npy')

In [9]:
data[999,-2,3,3]

78.81468442889253

In [10]:
data[30,30,30]

array([3.00000000e+01, 3.00000000e+01, 3.00000000e+01, 2.48975489e-06])

In [29]:
model = torch.load('2d_pred.pt')
model2 = torch.load('2d_pred_closehalf.pt')

In [22]:
model[25,-3,49]

tensor([9.6885], grad_fn=<SelectBackward0>)

In [23]:
a = 4
b = a
b += 3

In [33]:
model2.reshape(50,50,50)[30,-1,30]

tensor(96.4219, grad_fn=<SelectBackward0>)

In [28]:
1e-3

0.001

In [26]:
torch.tensor([[1,2,3]]) - torch.tensor([1])

tensor([[0, 1, 2]])